### ISSUE TITLE
Bug: pasting two links at once doesn't work

### ISSUE THREAD

**Issue by cmrd-senya** [visualjerk/quill-magic-url#15] opened 2020-04-02 16:08 UTC
Steps to reproduce.
1. Open 3rd party plain text editor
2. Type text "ONE http://example.com TWO http://google.com"
3. Copy text
4. Paste into quill with quill-magic-url extension

Expected Result:
http://example.com and http://google.com are detected as links

Actual Result:
Only the first link http://example.com is detected

**Comment by visualjerk** [comment] 2020-05-25 18:09
I am not able to reproduce it with the current version. Can you provide an example showcasing this issue? 

![double_link_example](https://user-images.githubusercontent.com/28823153/82835174-88411780-9ec3-11ea-87e7-f3e1708ba3d1.gif)

**Comment by cmrd-senya** [comment] 2020-05-26 10:33
I can't reproduce it either right now. Maybe there was some additional context but I don't remember it anymore.

**Comment by visualjerk** [comment] 2020-05-28 18:39
Alright, I close this for now.

**Closed by visualjerk** 2020-05-28 18:39 UTC
